glusterfs:
  image: 'tutum.co/seb24/tutum-glusterfs:latest'
  autoredeploy: true
  deployment_strategy: every_node
  roles:
    - global
  sequential_deployment: true
  tags:
    - glusterfs
  volumes_from:
    - glusterfsdata
glusterfsdata:
  image: 'busybox:latest'
  deployment_strategy: every_node
  tags:
    - glusterfs
  volumes:
    - /data
  command: 'ping localhost'
